/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameMaster } from "./GameMaster";
export type { GamerERC20 } from "./GamerERC20";
export type { Lock } from "./Lock";
