/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GameMaster__factory } from "./GameMaster__factory";
export { GamerERC20__factory } from "./GamerERC20__factory";
export { Lock__factory } from "./Lock__factory";
